name: Check format

on: 
  pull_request:

jobs:
  check_format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: pip install poetry && poetry install

    - name: Run Black
      run: black --check --line-length 79 .

    - name: Run isort
      run: isort --check-only --line-length 79 .

    - name: Run Flake8
      run: flake8 .

    - name: Run Mypy
      run: mypy .

    - name: Run Bandit
      run: bandit -r .